version: "3.9"

services:
  educoin-leader:
    build:
      context: ./educoin_project
    image: educoin-node
    container_name: educoin-leader
    environment:
      - NODE_ID=leader
      - IS_LEADER=true
      - PEER_NODES=http://educoin-node-1:8000,http://educoin-node-2:8000
      - LEADER_TOKEN=super-secret-token
      - EDUCOIN_DATA_PATH=/data/ledger.json
      - RING_TOKEN=ring-secret
      - RING_ENTRYPOINT=http://ring-node-a:8101
    volumes:
      - ./data/leader:/data
    ports:
      - "8000:8000"

  educoin-node-1:
    image: educoin-node
    depends_on:
      - educoin-leader
    environment:
      - NODE_ID=node-1
      - IS_LEADER=false
      - LEADER_URL=http://educoin-leader:8000
      - LEADER_TOKEN=super-secret-token
      - EDUCOIN_DATA_PATH=/data/ledger.json
      - RING_TOKEN=ring-secret
      - RING_ENTRYPOINT=http://ring-node-b:8102
    volumes:
      - ./data/node1:/data
    ports:
      - "8001:8000"

  educoin-node-2:
    image: educoin-node
    depends_on:
      - educoin-leader
    environment:
      - NODE_ID=node-2
      - IS_LEADER=false
      - LEADER_URL=http://educoin-leader:8000
      - LEADER_TOKEN=super-secret-token
      - EDUCOIN_DATA_PATH=/data/ledger.json
      - RING_TOKEN=ring-secret
      - RING_ENTRYPOINT=http://ring-node-c:8103
    volumes:
      - ./data/node2:/data
    ports:
      - "8002:8000"

  ring-node-a:
    build:
      context: .
      dockerfile: ring.Dockerfile
    environment:
      - RING_NODE_ID=101
      - RING_PORT=8101
      - NEXT_NODE=http://ring-node-b:8102
      - ENABLE_GUI=false
      - LEDGER_NOTIFY=http://educoin-leader:8000,http://educoin-node-1:8000,http://educoin-node-2:8000
      - LEDGER_MAP=101:leader@http://educoin-leader:8000,102:node-1@http://educoin-node-1:8000,103:node-2@http://educoin-node-2:8000
      - RING_TOKEN=ring-secret
    ports:
      - "8101:8101"

  ring-node-b:
    build:
      context: .
      dockerfile: ring.Dockerfile
    environment:
      - RING_NODE_ID=102
      - RING_PORT=8102
      - NEXT_NODE=http://ring-node-c:8103
      - ENABLE_GUI=false
      - LEDGER_NOTIFY=http://educoin-leader:8000,http://educoin-node-1:8000,http://educoin-node-2:8000
      - LEDGER_MAP=101:leader@http://educoin-leader:8000,102:node-1@http://educoin-node-1:8000,103:node-2@http://educoin-node-2:8000
      - RING_TOKEN=ring-secret
    ports:
      - "8102:8102"

  ring-node-c:
    build:
      context: .
      dockerfile: ring.Dockerfile
    environment:
      - RING_NODE_ID=103
      - RING_PORT=8103
      - NEXT_NODE=http://ring-node-a:8101
      - ENABLE_GUI=false
      - LEDGER_NOTIFY=http://educoin-leader:8000,http://educoin-node-1:8000,http://educoin-node-2:8000
      - LEDGER_MAP=101:leader@http://educoin-leader:8000,102:node-1@http://educoin-node-1:8000,103:node-2@http://educoin-node-2:8000
      - RING_TOKEN=ring-secret
    ports:
      - "8103:8103"
