services:
  educoin:
    build: .
    container_name: educoin
    environment:
      - PORT=8000
      - STATE_PATH=/data/state.json
      - CONFIG_PATH=/data/config.json
      # Ajuste opcional:
      # - NODE_NUM_ID=1234
      # - HEARTBEAT_INTERVAL=2.0
      # - MEMBER_TTL=8.0
    ports:
      - "8000:8000"
    volumes:
      - node_data:/data

volumes:
  node_data:
